export const GET_COLOURS_REQUEST = 'GET_COLOURS_REQUEST';
export const GET_COLOURS_SUCCESS = 'GET_COLOURS_SUCCESS';
export const GET_COLOURS_ERROR = 'GET_COLOURS_ERROR';

export const SAVE_COLOURS_REQUEST = 'SAVE_COLOURS_REQUEST';
export const SAVE_COLOURS_SUCCESS = 'SAVE_COLOURS_SUCCESS';
export const SAVE_COLOURS_ERROR = 'SAVE_COLOURS_ERROR';

export const ADD_COLOUR_REQUEST = 'ADD_COLOUR_REQUEST';
export const ADD_COLOUR_ERROR = 'ADD_COLOUR_ERROR';
export const ADD_COLOUR_SUCCESS = 'ADD_COLOUR_SUCCESS';
