export const GET_COLOURS_DOMAINS_REQUEST = 'GET_COLOURS_DOMAINS_REQUEST';
export const GET_COLOURS_DOMAINS_SUCCESS = 'GET_COLOURS_DOMAINS_SUCCESS';
export const GET_COLOURS_DOMAINS_ERROR = 'GET_COLOURS_DOMAINS_ERROR';

export const GET_COLOURS_DOMAIN_BY_ID_REQUEST = 'GET_COLOURS_DOMAIN_BY_ID_REQUEST';
export const GET_COLOURS_DOMAIN_BY_ID_SUCCESS = 'GET_COLOURS_DOMAIN_BY_ID_SUCCESS';
export const GET_COLOURS_DOMAIN_BY_ID_ERROR = 'GET_COLOURS_DOMAIN_BY_ID_ERROR';

export const REMOVE_COLOURS_DOMAIN_REQUEST = 'REMOVE_COLOURS_DOMAIN_REQUEST';
export const REMOVE_COLOURS_DOMAIN_SUCCESS = 'REMOVE_COLOURS_DOMAIN_SUCCESS';
export const REMOVE_COLOURS_DOMAIN_ERROR = 'REMOVE_COLOURS_DOMAIN_ERROR';

export const ADD_COLOURS_DOMAIN_REQUEST = 'ADD_COLOURS_DOMAIN_REQUEST';
export const ADD_COLOURS_DOMAIN_SUCCESS = 'ADD_COLOURS_DOMAIN_SUCCESS';
export const ADD_COLOURS_DOMAIN_ERROR = 'ADD_COLOURS_DOMAIN_ERROR';
