export const DICT_REMOVE_REQUEST = 'DICT_REMOVE_REQUEST';
export const DICT_REMOVE_SUCCESS = 'DICT_REMOVE_SUCCESS';
export const DICT_REMOVE_ERROR = 'DICT_REMOVE_ERROR';

export const GET_DICT_BY_ID_REQUEST = 'GET_DICT_BY_ID_REQUEST';
export const GET_DICT_BY_ID_SUCCESS = 'GET_DICT_BY_ID_SUCCESS';
export const GET_DICT_BY_ID_ERROR = 'GET_DICT_BY_ID_ERROR';

export const ADD_NEW_DICT_REQUEST = 'ADD_NEW_DICT_REQUEST';
export const ADD_NEW_DICT_SUCCESS = 'ADD_NEW_DICT_SUCCESS';
export const ADD_NEW_DICT_ERROR = 'ADD_NEW_DICT_ERROR';
