export const DATASET_REQUEST = 'DATASET_REQUEST';
export const DATASET_REQUEST_SUCCESS = 'DATASET_REQUEST_SUCCESS';
export const DATASET_REQUEST_ERROR = 'DATASET_REQUEST_ERROR';

export const APP_INIT = 'APP_INIT';
