export const DICTS_REQUEST = 'DICTS_REQUEST';
export const DICTS_REQUEST_SUCCESS = 'DICTS_REQUEST_SUCCESS';
export const DICTS_REQUEST_ERROR = 'DICTS_REQUEST_ERROR';

export const APP_INIT = 'APP_INIT';
