export const GET_DOMAINS_REQUEST = 'GET_DOMAINS_REQUEST';
export const GET_DOMAINS_SUCCESS = 'GET_DOMAINS_SUCCESS';
export const GET_DOMAINS_ERROR = 'GET_DOMAINS_ERROR';

export const GET_DOMAIN_BY_ID_REQUEST = 'GET_DOMAIN_BY_ID_REQUEST';
export const GET_DOMAIN_BY_ID_SUCCESS = 'GET_DOMAIN_BY_ID_SUCCESS';
export const GET_DOMAIN_BY_ID_ERROR = 'GET_DOMAIN_BY_ID_ERROR';

export const REMOVE_DOMAIN_REQUEST = 'REMOVE_DOMAIN_REQUEST';
export const REMOVE_DOMAIN_SUCCESS = 'REMOVE_DOMAIN_SUCCESS';
export const REMOVE_DOMAIN_ERROR = 'REMOVE_DOMAIN_ERROR';

export const ADD_DOMAIN_REQUEST = 'ADD_DOMAIN_REQUEST';
export const ADD_DOMAIN_SUCCESS = 'ADD_DOMAIN_SUCCESS';
export const ADD_DOMAIN_ERROR = 'ADD_DOMAIN_ERROR';

export const SAVE_DOMAIN_BY_ID_REQUEST = 'SAVE_DOMAIN_BY_ID_REQUEST';
export const SAVE_DOMAIN_BY_ID_SUCCESS = 'SAVE_DOMAIN_BY_ID_SUCCESS';
export const SAVE_DOMAIN_BY_ID_ERROR = 'SAVE_DOMAIN_BY_ID_ERROR';
