export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST';
export const PRODUCTS_REQUEST_SUCCESS = 'PRODUCTS_REQUEST_SUCCESS';
export const PRODUCTS_REQUEST_ERROR = 'PRODUCTS_REQUEST_ERROR';

export const PRODUCT_REMOVE_REQUEST = 'PRODUCT_REMOVE_REQUEST';
export const PRODUCT_REMOVE_SUCCESS = 'PRODUCT_REMOVE_SUCCESS';
export const PRODUCT_REMOVE_ERROR = 'PRODUCT_REMOVE_ERROR';

export const GET_PRODUCT_BY_ID_REQUEST = 'GET_PRODUCT_BY_ID_REQUEST';
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS';
export const GET_PRODUCT_BY_ID_ERROR = 'GET_PRODUCT_BY_ID_ERROR';

export const ADD_NEW_PRODUCT_REQUEST = 'ADD_NEW_PRODUCT_REQUEST';
export const ADD_NEW_PRODUCT_SUCCESS = 'ADD_NEW_PRODUCT_SUCCESS';
export const ADD_NEW_PRODUCT_ERROR = 'ADD_NEW_PRODUCT_ERROR';

export const SAVE_PRODUCT_BY_ID_REQUEST = 'SAVE_PRODUCT_BY_ID_REQUEST';
export const SAVE_PRODUCT_BY_ID_SUCCESS = 'SAVE_PRODUCT_BY_ID_SUCCESS';
export const SAVE_PRODUCT_BY_ID_ERROR = 'SAVE_PRODUCT_BY_ID_ERROR';
